; PlatformIO Project Configuration File
;
; Build and upload:
;   pio run -e uno_r4_wifi --target upload
;
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_speed = 115200

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
extra_scripts = pre:scripts/version.py
build_flags =
    -I include/uno_r4_wifi
    -DAPP_VERSION=\"1.0\"
lib_deps =
    bblanchon/ArduinoJson
    olikraus/U8g2@^2.35.10

