; PlatformIO Project Configuration File
;
; Build and upload:
;   pio run -e uno_r4_wifi              --target upload
;   pio run -e esp32dev                 --target upload
;   pio run -e esp32c6_waveshare_lcd    --target upload
;
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_speed = 115200

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
extra_scripts = pre:scripts/version.py
build_flags =
    -I include/uno_r4_wifi
    -DAPP_VERSION=\"1.4\"
lib_deps =
    bblanchon/ArduinoJson
    olikraus/U8g2@^2.35.10

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
extra_scripts = pre:scripts/version.py
build_flags =
    -I include/esp32dev
    -DAPP_VERSION=\"1.4\"
lib_deps =
    bblanchon/ArduinoJson
    olikraus/U8g2@^2.35.10

[env:esp32c6_waveshare_lcd]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = waveshare_esp32c6_lcd
framework = arduino
extra_scripts = pre:scripts/version.py
build_flags =
    -I include/esp32c6_waveshare_lcd
    -DAPP_VERSION=\"1.4\"
    -DWAVESHARE_ESP32C6_LCD=1
lib_deps =
    bblanchon/ArduinoJson
    lovyan03/LovyanGFX
